import Head from "next/head"
import { Inter } from "next/font/google"
import { Container, Flex, Heading, Input, Text } from "@chakra-ui/react"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				as="main"
				w="100vw"
				h="100vh"
				p="30px"
				className={inter.className}
				bg="white"
			>
				<Container align="center" px="1" maxW="1000px">
					<Heading>Real Debrid FAQ</Heading>
					<Text pb="15px" maxW="400px">
						A frontend for Real Debrid's FAQ page which actually shows the
						answers.
					</Text>
					<Input maxW="500px" placeholder="Search Real Debrid FAQ..." />
				</Container>
			</Flex>
		</>
	)
}
